apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          securityContext:
          image: "backend-backend:latest"
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: "database"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "admin"
            - name: DB_NAME
              value: "wevester_todo"
